### ISSUE TITLE
Guilds rate limited

### ISSUE THREAD

**Issue by joobei** [QGIsK/passport-discord#2]
Despite having the guilds scope it seems like guilds are never being returned because the discord API rate limits it seems and I get a 429 in this line:
https://github.com/QGIsK/passport-discord/blob/fb48474865e2a0d894ab4508fccc08b7eb426c8b/lib/strategy.js#L98-L99

I am currently trying to find a workaround and will submit a pull request if I do.

**Comment by joobei** [comment]
The problem does not occur when I run Express.js from Visual studio in debug mode. I am assuming that, because the code runs marginally slower in the debugger, the discord API does not get rate limited.

**Comment by QGIsK** [comment]
Lmk if you find away around it, if not I can try take a look.

PR's are always welcome ;)

**Comment by QGIsK** [comment]
Released a new version that should (hopefully) fix this.


Update
```bash
npm i @qgisk/passport-discord@0.0.2
```

Lmk how it goes.

**Comment by joobei** [comment]
it works now thank you!
