### ISSUE TITLE
Prompt none is not working

### ISSUE THREAD

**Issue by typhoon11** [QGIsK/passport-discord#3]
When using prompt as none it's not taking that and login page is coming

**Comment by QGIsK** [comment]
Hey! You need to set the prompt in your redirect middleware, I'll update the examples and readme to make this more clear.

Heres an example

```javascript
const prompt = "consent"
app.get(
    "/discord/redirect",
    passport.authenticate("discord", { scope: scopes, prompt })
);
```

More information can be found here https://stackoverflow.com/a/63043207

And for Discord's documentation regarding prompts see https://discord.com/developers/docs/topics/oauth2#authorization-code-grant
